### ISSUE TITLE
README not updated

### ISSUE THREAD

**Issue by benzebra** [micheledinelli/aculei-fe#13]

**Comment by micheledinelli** [comment]
<img width="1440" alt="archive-page" src="https://github.com/micheledinelli/aculei-fe/assets/95191347/79711b86-6210-4cc8-acd8-6d18fa83050e">
<img width="1440" alt="detail-1" src="https://github.com/micheledinelli/aculei-fe/assets/95191347/094dcbf6-fa2a-4fc9-b36c-ddd3741fcbb2">
<img width="1440" alt="detail-2" src="https://github.com/micheledinelli/aculei-fe/assets/95191347/3d9d7df8-1378-4919-9fa4-010fc9befb93">
<img width="1440" alt="landiing-page" src="https://github.com/micheledinelli/aculei-fe/assets/95191347/a914253d-6072-4aab-9c25-2a3d9e57a60f">
<img width="1440" alt="loading-gif" src="https://github.com/micheledinelli/aculei-fe/assets/95191347/9c0e6eff-0aba-4be2-9815-1cc6ab082443">
